### PR TITLE
Typescript definitions propositions

### PR DESCRIPTION
**Pull request by urosjarc**
Info:

 - https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html
 - https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

Related:

 -  https://github.com/BigstickCarpet/postman-bdd/issues/6
 - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15691

### CODE REVIEW

**Comment by urosjarc** [comment]
@BigstickCarpet: I don't have time to complete this pull request 100%. Please resolve todos, and write tests like I did in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15691

**Comment by BigstickCarpet** [comment]
Thanks for the PR, @urosjarc!  I'll try to take a detailed look at it this weekend and get it merged

**Comment by urosjarc** [comment]
I will make additional PR, while I will developing postman tests, this PR is youst initial arhitecture for ts definitions.

**Comment by BigstickCarpet** [comment]
@urosjarc - Sounds good!  I'm going to make a couple minor changes to fix some [build errors](https://ci.appveyor.com/project/BigstickCarpet/postman-bdd/build/1.0.23/job/gchfff421rb78aff#L1716), so be sure to pull my changes before you make more changes

**Comment by urosjarc** [comment]
@BigstickCarpet Those build errors are from typescript tests. Tests will all pass when `types/index.d.ts` will match 100% with `types/postman-bdd-tests.ts`. Please see how to create good `d.ts` tests here [where is my pull request for postman-sandbox](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15691/files#diff-ad9e74157492b3519701d0d5d130b18d).

**Pull request merged**
